#@TYPE: Machine
#@NAME: Calixto iMX8M Plus Optima with LPDDR4
#@SOC: i.MX8MP
#@DESCRIPTION: Machine configuration for Calixto i.MX 8M Plus Optima SOM  with LPDDR4
#@MAINTAINER:

PREFERRED_PROVIDER_virtual/bootloader = "u-boot-calixto-nxp"
PREFERRED_PROVIDER_u-boot = "u-boot-calixto-nxp"
require include/imx8mp-calixto.inc

PREFERRED_PROVIDER_virtual/kernel = "linux-calixto-nxp"

# The device tree name is implicit for LPDDR4, so can't use MACHINE here
KERNEL_DEVICETREE_BASENAME = "imx8mp-calixto-optima_4GB"
UBOOT_DTB_NAME = "imx8mp-calixto-optima_4GB.dtb"

# MAP SOURCE DTB TO STANDARDIZED NAME ON THE BOOT PARTITION:
# Syntax: "source_file_built_by_kernel.dtb;destination_file_on_boot_partition.dtb"
IMAGE_BOOT_FILES:append = " ${KERNEL_DEVICETREE_BASENAME}.dtb;imx8mp-calixto-optima.dtb"

# NXP kernel has additional DTB files for various board configuration and
# derivates. Include them here for NXP BSP only
KERNEL_DEVICETREE:append:use-nxp-bsp = " \
   freescale/imx8mp-calixto-optima_4GB-csi2-lvds.dtb \
   freescale/imx8mp-calixto-optima_4GB-mipidsi.dtb \
   freescale/imx8mp-calixto-optima_4GB-csi2-mipidsi.dtb \
   freescale/imx8mp-calixto-optima_4GB-dualcsi-lvds.dtb \
   freescale/imx8mp-calixto-optima_4GB-dualcsi-mipidsi.dtb \
"

UBOOT_CONFIG_BASENAME = "imx8mp_calixto_optima_4gb"
#UBOOT_CONFIG ??= "sd"
#UBOOT_CONFIG[sd]   = "${UBOOT_CONFIG_BASENAME}_defconfig"
UBOOT_CONFIG[fspi] = "${UBOOT_CONFIG_BASENAME}_defconfig"
UBOOT_CONFIG[ndm]  = "${UBOOT_CONFIG_BASENAME}_ndm_defconfig"

# Set DDR FIRMWARE
DDR_FIRMWARE_VERSION = "202006"
DDR_FIRMWARE_NAME = " \
    lpddr4_pmu_train_1d_dmem_${DDR_FIRMWARE_VERSION}.bin \
    lpddr4_pmu_train_1d_imem_${DDR_FIRMWARE_VERSION}.bin \
    lpddr4_pmu_train_2d_dmem_${DDR_FIRMWARE_VERSION}.bin \
    lpddr4_pmu_train_2d_imem_${DDR_FIRMWARE_VERSION}.bin \
"

IMXBOOT_TARGETS_BASENAME = "flash_evk"

# Mainline BSP doesn't support LPDDR4 so it must be set to nxp.
# Also this machine isn't supported by u-boot-fslc but imx8mn-evk.inc already
# set the bootloader to u-boot-imx instead when NXP BSP is used.
IMX_DEFAULT_BSP = "nxp"
